/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type FeeStruct = {
  id: BigNumberish;
  percentage: BigNumberish;
  amount: BigNumberish;
  feeType: string;
  cumulative: boolean;
  noCombine: string[];
};

export type FeeStructOutput = [
  BigNumber,
  number,
  number,
  string,
  boolean,
  string[]
] & {
  id: BigNumber;
  percentage: number;
  amount: number;
  feeType: string;
  cumulative: boolean;
  noCombine: string[];
};

export type ResourceStruct = {
  id: BigNumberish;
  name: string;
  symbol: string;
  measurementUnit: string;
};

export type ResourceStructOutput = [BigNumber, string, string, string] & {
  id: BigNumber;
  name: string;
  symbol: string;
  measurementUnit: string;
};

export type ConstructorParamsStruct = {
  askFee: FeeStruct;
  bidFee: FeeStruct;
  marginFee: FeeStruct;
  numberOfPeriodsPerDay: BigNumberish;
  periodDurationInMinutes: BigNumberish;
  periodsStartHour: BigNumberish;
  periodsStartMinute: BigNumberish;
  treasuryWallet: string;
  escrowWallet: string;
  resources: ResourceStruct[];
  sellers: string[];
  buyers: string[];
};

export type ConstructorParamsStructOutput = [
  FeeStructOutput,
  FeeStructOutput,
  FeeStructOutput,
  number,
  number,
  number,
  number,
  string,
  string,
  ResourceStructOutput[],
  string[],
  string[]
] & {
  askFee: FeeStructOutput;
  bidFee: FeeStructOutput;
  marginFee: FeeStructOutput;
  numberOfPeriodsPerDay: number;
  periodDurationInMinutes: number;
  periodsStartHour: number;
  periodsStartMinute: number;
  treasuryWallet: string;
  escrowWallet: string;
  resources: ResourceStructOutput[];
  sellers: string[];
  buyers: string[];
};

export type ResourceAskStruct = {
  id: BigNumberish;
  resourceId: BigNumberish;
  asker: string;
  units: BigNumberish;
  purity: BigNumberish;
  askPPU: BigNumberish;
};

export type ResourceAskStructOutput = [
  BigNumber,
  number,
  string,
  number,
  number,
  BigNumber
] & {
  id: BigNumber;
  resourceId: number;
  asker: string;
  units: number;
  purity: number;
  askPPU: BigNumber;
};

export type ResourceBidStruct = {
  id: BigNumberish;
  bidder: string;
  resourceId: BigNumberish;
  units: BigNumberish;
  purity: BigNumberish;
  bidPPU: BigNumberish;
};

export type ResourceBidStructOutput = [
  BigNumber,
  string,
  number,
  number,
  number,
  BigNumber
] & {
  id: BigNumber;
  bidder: string;
  resourceId: number;
  units: number;
  purity: number;
  bidPPU: BigNumber;
};

export interface ControllerInterface extends utils.Interface {
  functions: {
    "addBuyer(address)": FunctionFragment;
    "addSeller(address)": FunctionFragment;
    "askFee()": FunctionFragment;
    "bidFee()": FunctionFragment;
    "getAsks()": FunctionFragment;
    "getBids()": FunctionFragment;
    "getBuyers()": FunctionFragment;
    "getResources()": FunctionFragment;
    "getSellers()": FunctionFragment;
    "marginFee()": FunctionFragment;
    "numberOfPeriodsPerDay()": FunctionFragment;
    "periodDurationInMinutes()": FunctionFragment;
    "periodsStartHour()": FunctionFragment;
    "periodsStartMinute()": FunctionFragment;
    "removeBuyer(address)": FunctionFragment;
    "removeSeller(address)": FunctionFragment;
    "setEscrow(address)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "setTreasury(address)": FunctionFragment;
    "submitAsk(uint16,uint16,uint16,uint256)": FunctionFragment;
    "submitBid(uint16,uint16,uint16,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addBuyer"
      | "addSeller"
      | "askFee"
      | "bidFee"
      | "getAsks"
      | "getBids"
      | "getBuyers"
      | "getResources"
      | "getSellers"
      | "marginFee"
      | "numberOfPeriodsPerDay"
      | "periodDurationInMinutes"
      | "periodsStartHour"
      | "periodsStartMinute"
      | "removeBuyer"
      | "removeSeller"
      | "setEscrow"
      | "setOwner"
      | "setTreasury"
      | "submitAsk"
      | "submitBid"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "addBuyer", values: [string]): string;
  encodeFunctionData(functionFragment: "addSeller", values: [string]): string;
  encodeFunctionData(functionFragment: "askFee", values?: undefined): string;
  encodeFunctionData(functionFragment: "bidFee", values?: undefined): string;
  encodeFunctionData(functionFragment: "getAsks", values?: undefined): string;
  encodeFunctionData(functionFragment: "getBids", values?: undefined): string;
  encodeFunctionData(functionFragment: "getBuyers", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getResources",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSellers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "marginFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "numberOfPeriodsPerDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "periodDurationInMinutes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "periodsStartHour",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "periodsStartMinute",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "removeBuyer", values: [string]): string;
  encodeFunctionData(
    functionFragment: "removeSeller",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setEscrow", values: [string]): string;
  encodeFunctionData(functionFragment: "setOwner", values: [string]): string;
  encodeFunctionData(functionFragment: "setTreasury", values: [string]): string;
  encodeFunctionData(
    functionFragment: "submitAsk",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addBuyer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addSeller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "askFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bidFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAsks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBuyers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getResources",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSellers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "marginFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberOfPeriodsPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "periodDurationInMinutes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "periodsStartHour",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "periodsStartMinute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeBuyer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSeller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitAsk", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;

  events: {};
}

export interface Controller extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ControllerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addBuyer(
      buyer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addSeller(
      seller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    askFee(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number, string, boolean] & {
        id: BigNumber;
        percentage: number;
        amount: number;
        feeType: string;
        cumulative: boolean;
      }
    >;

    bidFee(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number, string, boolean] & {
        id: BigNumber;
        percentage: number;
        amount: number;
        feeType: string;
        cumulative: boolean;
      }
    >;

    getAsks(overrides?: CallOverrides): Promise<[ResourceAskStructOutput[]]>;

    getBids(overrides?: CallOverrides): Promise<[ResourceBidStructOutput[]]>;

    getBuyers(overrides?: CallOverrides): Promise<[string[]]>;

    getResources(overrides?: CallOverrides): Promise<[ResourceStructOutput[]]>;

    getSellers(overrides?: CallOverrides): Promise<[string[]]>;

    marginFee(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number, string, boolean] & {
        id: BigNumber;
        percentage: number;
        amount: number;
        feeType: string;
        cumulative: boolean;
      }
    >;

    numberOfPeriodsPerDay(overrides?: CallOverrides): Promise<[number]>;

    periodDurationInMinutes(overrides?: CallOverrides): Promise<[number]>;

    periodsStartHour(overrides?: CallOverrides): Promise<[number]>;

    periodsStartMinute(overrides?: CallOverrides): Promise<[number]>;

    removeBuyer(
      buyer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeSeller(
      seller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setEscrow(
      newEscrow: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTreasury(
      newTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    submitAsk(
      resourceId: BigNumberish,
      units: BigNumberish,
      purity: BigNumberish,
      askPPU: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    submitBid(
      resourceId: BigNumberish,
      units: BigNumberish,
      purity: BigNumberish,
      bidPPU: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addBuyer(
    buyer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addSeller(
    seller: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  askFee(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, number, string, boolean] & {
      id: BigNumber;
      percentage: number;
      amount: number;
      feeType: string;
      cumulative: boolean;
    }
  >;

  bidFee(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, number, string, boolean] & {
      id: BigNumber;
      percentage: number;
      amount: number;
      feeType: string;
      cumulative: boolean;
    }
  >;

  getAsks(overrides?: CallOverrides): Promise<ResourceAskStructOutput[]>;

  getBids(overrides?: CallOverrides): Promise<ResourceBidStructOutput[]>;

  getBuyers(overrides?: CallOverrides): Promise<string[]>;

  getResources(overrides?: CallOverrides): Promise<ResourceStructOutput[]>;

  getSellers(overrides?: CallOverrides): Promise<string[]>;

  marginFee(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, number, string, boolean] & {
      id: BigNumber;
      percentage: number;
      amount: number;
      feeType: string;
      cumulative: boolean;
    }
  >;

  numberOfPeriodsPerDay(overrides?: CallOverrides): Promise<number>;

  periodDurationInMinutes(overrides?: CallOverrides): Promise<number>;

  periodsStartHour(overrides?: CallOverrides): Promise<number>;

  periodsStartMinute(overrides?: CallOverrides): Promise<number>;

  removeBuyer(
    buyer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeSeller(
    seller: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setEscrow(
    newEscrow: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOwner(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTreasury(
    newTreasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  submitAsk(
    resourceId: BigNumberish,
    units: BigNumberish,
    purity: BigNumberish,
    askPPU: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  submitBid(
    resourceId: BigNumberish,
    units: BigNumberish,
    purity: BigNumberish,
    bidPPU: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addBuyer(buyer: string, overrides?: CallOverrides): Promise<void>;

    addSeller(seller: string, overrides?: CallOverrides): Promise<void>;

    askFee(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number, string, boolean] & {
        id: BigNumber;
        percentage: number;
        amount: number;
        feeType: string;
        cumulative: boolean;
      }
    >;

    bidFee(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number, string, boolean] & {
        id: BigNumber;
        percentage: number;
        amount: number;
        feeType: string;
        cumulative: boolean;
      }
    >;

    getAsks(overrides?: CallOverrides): Promise<ResourceAskStructOutput[]>;

    getBids(overrides?: CallOverrides): Promise<ResourceBidStructOutput[]>;

    getBuyers(overrides?: CallOverrides): Promise<string[]>;

    getResources(overrides?: CallOverrides): Promise<ResourceStructOutput[]>;

    getSellers(overrides?: CallOverrides): Promise<string[]>;

    marginFee(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, number, string, boolean] & {
        id: BigNumber;
        percentage: number;
        amount: number;
        feeType: string;
        cumulative: boolean;
      }
    >;

    numberOfPeriodsPerDay(overrides?: CallOverrides): Promise<number>;

    periodDurationInMinutes(overrides?: CallOverrides): Promise<number>;

    periodsStartHour(overrides?: CallOverrides): Promise<number>;

    periodsStartMinute(overrides?: CallOverrides): Promise<number>;

    removeBuyer(buyer: string, overrides?: CallOverrides): Promise<void>;

    removeSeller(seller: string, overrides?: CallOverrides): Promise<void>;

    setEscrow(newEscrow: string, overrides?: CallOverrides): Promise<void>;

    setOwner(newOwner: string, overrides?: CallOverrides): Promise<void>;

    setTreasury(newTreasury: string, overrides?: CallOverrides): Promise<void>;

    submitAsk(
      resourceId: BigNumberish,
      units: BigNumberish,
      purity: BigNumberish,
      askPPU: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    submitBid(
      resourceId: BigNumberish,
      units: BigNumberish,
      purity: BigNumberish,
      bidPPU: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addBuyer(
      buyer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addSeller(
      seller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    askFee(overrides?: CallOverrides): Promise<BigNumber>;

    bidFee(overrides?: CallOverrides): Promise<BigNumber>;

    getAsks(overrides?: CallOverrides): Promise<BigNumber>;

    getBids(overrides?: CallOverrides): Promise<BigNumber>;

    getBuyers(overrides?: CallOverrides): Promise<BigNumber>;

    getResources(overrides?: CallOverrides): Promise<BigNumber>;

    getSellers(overrides?: CallOverrides): Promise<BigNumber>;

    marginFee(overrides?: CallOverrides): Promise<BigNumber>;

    numberOfPeriodsPerDay(overrides?: CallOverrides): Promise<BigNumber>;

    periodDurationInMinutes(overrides?: CallOverrides): Promise<BigNumber>;

    periodsStartHour(overrides?: CallOverrides): Promise<BigNumber>;

    periodsStartMinute(overrides?: CallOverrides): Promise<BigNumber>;

    removeBuyer(
      buyer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeSeller(
      seller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setEscrow(
      newEscrow: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTreasury(
      newTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    submitAsk(
      resourceId: BigNumberish,
      units: BigNumberish,
      purity: BigNumberish,
      askPPU: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    submitBid(
      resourceId: BigNumberish,
      units: BigNumberish,
      purity: BigNumberish,
      bidPPU: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addBuyer(
      buyer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addSeller(
      seller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    askFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bidFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAsks(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBids(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBuyers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getResources(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSellers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    marginFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numberOfPeriodsPerDay(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    periodDurationInMinutes(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    periodsStartHour(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    periodsStartMinute(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeBuyer(
      buyer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeSeller(
      seller: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setEscrow(
      newEscrow: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTreasury(
      newTreasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    submitAsk(
      resourceId: BigNumberish,
      units: BigNumberish,
      purity: BigNumberish,
      askPPU: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    submitBid(
      resourceId: BigNumberish,
      units: BigNumberish,
      purity: BigNumberish,
      bidPPU: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
